version: "3.9"

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    entrypoint: /usr/local/bin/entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - .docker:/usr/local/bin
    environment:
      - TZ=America/New_York
