version: "3.9"

services:

  nginx:
    image: nginx
    ports:
      - 8080:8080
      - 8004:8004
    networks:
      - php_nginx

  php:
    image: php:fpm
    ports:
      - 9000:9000
    volumes:
      - ./php:/var/www/html
    networks:
      - php_nginx

networks:
  php_nginx:
    driver: bridge