version: "3.9"

services:

  nginx:
    image: nginx
    ports:
      - 8080:8080
    networks:
      - mongo_node

  alurabooks1:
    image: aluradocker/alura-books:1.0
    ports:
      - 3001:3000
    networks:
      - mongo_node

  alurabooks2:
    image: aluradocker/alura-books:1.0
    ports:
      - 3002:3000
    networks:
      - mongo_node

  meu-mongo:
    image: mongo:4.4.6
    networks:
      - mongo_node

networks:
  mongo_node:
    driver: bridge

